version: '3'
services:
    db:
        image: mysql
        # dont need to expose port if we don't want to access mysql outside
        # ports:
        #    - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: springuser
            MYSQL_PASSWORD: ThePassword
            MYSQL_DATABASE: db_example
    spring:
        depends_on:
            - db
        build: .
        ports:
            - "8080:8080"
        environment:
            MYSQL_HOST: db